name: CI

on: [push]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/checkout@v2
      - name: npm install, build and test
        run: |
          npm install
          node build --arch x64
      - name: Upload the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: 'build/out/*.zip'
